### ISSUE TITLE
Contributors section

### ISSUE THREAD

**Issue by adanj27** [adanj27/Web-Dev-Hut-Open-Source#24]
Buscar la carpeta home en componentes y crear el componente Correspondiente en la misma carpeta y exportarla al archivo Home.jsx de la carpeta pages.
P.D. Seguir el diseño de figma
https://www.figma.com/file/CVUWo2Up36fZrrC21cRi2J/Dise%C3%B1o-mockups?type=design&node-id=62%3A2&t=o4j73QTszOHtS7M0-1

![Image](https://user-images.githubusercontent.com/117919468/236701943-d695f4b5-3f05-465c-a2d1-4ace995f1b42.PNG)

**Comment by FOWMind** [comment]
Qué cambios hacen falta?
